spring:
  application:
    name: gulimall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 60.204.249.234:8848

    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route2
          uri: http://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://gulimall-product # 注册中心的服务
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast # 路由给renren-fast  lb代表负载均衡
          predicates:  # 什么情况路由它
            - Path=/api/** # 默认前端项目都带api前缀，就是我们前面的localhost:80/api
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment} # 把/api/* 改变成 /renren-fast/*