server:
  port: 12000

spring:
  application:
    name: gulimall-third-party

  cloud:
    nacos:
      discovery:
        server-addr: 60.204.249.234:8848
#    alicloud:
#      access-key:
#      secret-key:
#      oss:
#        bucket: gulimall-dkui
#        endpoint: oss-cn-shanghai.aliyuncs.com

logging:
  level:
    com.atguigu.gulimall.thirdparty: debug